name: 'PR Label - Approval'

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: write

jobs:
  label-when-approved:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Add approval label
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['approved-by-team']
            })
